version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:5050"
      REACT_APP_URL: "http://localhost:3000"
  backend:
    build: ./server
    ports:
      - "5050:5050"
    environment:
      PORT: "5050"
      MYSQL_ROOT_PASSWORD: "harish"
      MYSQL_HOST: "ecommerce_db_1"
      MYSQL_USER: "harish"
      MYSQL_PASSWORD: "harish"
      MYSQL_DATABASE: "list"
      SOLR_HOST: "ecommerce_solr_1"
      SOLR_CORE: "mycore"
    depends_on:
      - db
      - solr
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "harish"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  solr:
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/lib/solr
volumes:
  mysql-data:
  solr-data:
