version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:5050"
      REACT_APP_URL: "http://localhost:3000"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - MYSQL_HOST=sql6.freesqldatabase.com
      - MYSQL_USER=sql6685208
      - MYSQL_PASSWORD=NZ6k2HWftb
      - MYSQL_DATABASE=sql6685208
      - SOLR_HOST=solr
      - SOLR_CORE=mycore
      - SOLR_PORT=8983
    depends_on:
      - solr
    networks:
      - host

  solr:
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - ./conf:/opt/solr/server/solr/configsets/mycore_conf
    command: >
      bash -c "
        rm -rf /var/solr/data/mycore &&
        exec solr-foreground &
        sleep 5 &&
        if [ ! -f /opt/solr/server/solr/configsets/mycore_conf/conf/schema.xml ]; then
          cp /opt/solr/server/solr/configsets/mycore_conf/conf/schema.xml /opt/solr/server/solr/configsets/mycore_conf/conf/;
        fi &&
        bin/solr create -c mycore -d /opt/solr/server/solr/configsets/mycore_conf && wait
      "
    networks:
      - host
networks:
  host:
